Better dev build process.

diff --git a/misc/build-all b/misc/build-all
--- a/misc/build-all
+++ b/misc/build-all
@@ -2,6 +2,14 @@
 
 set -xe
 
+arg_buld_name="${1:?Missing build name argument.}"
+arg_cpu_count="$(nproc)"
+
+if [[ -z "${arg_cpu_count}" ]]; then
+  echo "could not get cpu count"
+  exit 1
+fi
+
 if ! [[ -d /build/source ]]; then
   rm -rf /build /prefix || :
   cp -rp /deploy/build /
@@ -9,24 +17,26 @@ if ! [[ -d /build/source ]]; then
   cd /build
 fi
 
-rsync-update /data/libtorrent/ /build/source/
+rsync-update /data/${arg_buld_name}/ /build/source/
 
 cd /build/source
 
 if ! [[ -f "./configure" ]]; then
-  echo -e "\033[0;32mlibtorrent autogen.sh\033[0m"
+  echo -e "\033[0;32m${arg_buld_name} autogen.sh\033[0m"
   ./autogen.sh
 fi
 
 cd /build/output
 
 if ! [[ -f "./config.h" ]]; then
-  echo -e "\033[0;32mlibtorrent configure\033[0m"
+  echo -e "\033[0;32m${arg_buld_name} configure\033[0m"
   . /env.configure
   /build/source/configure --prefix=/prefix --disable-backtrace
 fi
 
-make
-make install
-make check TESTS=
-make check
+make_args=(-j $(( ${arg_cpu_count} * 2 )) )
+
+make "${make_args[@]}"
+make "${make_args[@]}" install
+make "${make_args[@]}" check TESTS=
+make "${make_args[@]}" check
