Use buildkit mount bind to cache packages in a dedicated image.

diff --git a/misc/pkg-add b/misc/pkg-add
--- a/misc/pkg-add
+++ b/misc/pkg-add
@@ -4,6 +4,33 @@ set -e
 
 arg_packages="${@}"
 
-apk add --no-network ${arg_packages} || apk add ${arg_packages}
+rm -rf /var/cache/apk /var/cache/apk-deploy &> /dev/null || :
+mkdir -p /var/cache/apk /var/cache/apk-deploy
 
-find /apk-cache -exec touch -r /etc/alpine-release {} \;
+if [ ! -h /etc/apk/cache ]; then
+  ln -s /var/cache/apk /etc/apk/cache
+fi
+
+cd /var/cache/apk-stage
+find . -type d -exec mkdir -p "/var/cache/apk/{}" \;
+find . -type f -exec ln -s "/var/cache/apk-stage/{}" "/var/cache/apk/{}" \;
+
+# ls -l /var/cache/apk-stage || :
+
+if apk add --no-network ${arg_packages}; then
+  echo "installed all packages from cache"
+  exit 0
+fi
+
+if ! apk add ${arg_packages}; then
+  echo "failed to install some packages from remote repository"
+  exit 1
+fi
+
+echo "installed all packages from remote repository"
+
+cd /var/cache/apk
+find . -type d -exec mkdir -p "/var/cache/apk-deploy/{}" \;
+find . -type f -exec mv "{}" "/var/cache/apk-deploy/{}" \;
+
+rm -rf /var/cache/apk
