Optimized build process.

diff --git a/functions/docker b/functions/docker
--- a/functions/docker
+++ b/functions/docker
@@ -1,8 +1,8 @@
 #!/usr/bin/env bash
 
 set -e
+[[ -n "${included_rdo_docker}" ]] && echo "rdo_docker already included" && exit 1
 local included_rdo_docker="yes"
-# print_normal "included rdo_docker"
 
 rdo_docker() {
   local cmd="${1}"; shift || :
@@ -27,6 +27,9 @@ rdo_docker() {
       ;;
     images)
       rdo_docker_images "${@}"
+      ;;
+    inspect)
+      rdo_docker_inspect "${@}"
       ;;
     stage)
       rdo_docker_stage "${@}"
@@ -235,6 +238,46 @@ rdo_docker_children() {
 
 rdo_docker_images() {
   :
+}
+
+rdo_docker_inspect() {
+  local arg_format=()
+
+  while [[ -n "${1}" ]]; do
+    case "${1}" in
+      --id)
+        arg_format+=("{{ .Id }}")
+        shift ;;
+      --help|-h)
+        echo "Usage: rdo docker inspect COMMAND"
+        echo
+        echo "Inspect docker container"
+        echo
+        echo "Options:"
+        echo "      --id  Print full hash id"
+        echo
+        echo "Run 'do inspect COMMAND --help' for more information on a command."
+      ;;
+      *)
+        if [[ -z "${1##-*}" ]]; then
+          echo "do docker inspect: invalid parameters: ${@}" 2> /dev/null
+          exit 1
+        fi
+
+        break
+        ;;
+    esac
+  done
+
+  if (( ${#} == 0 )); then
+    return 0
+  fi
+
+  if [[ -z "${arg_format[@]}" ]]; then
+    arg_format+=("{{ .Id }}")
+  fi
+
+  docker inspect --format "${arg_format[@]}" "${@}"
 }
 
 rdo_docker_stage() {
