New docker build system.

diff --git a/functions/env b/functions/env
--- a/functions/env
+++ b/functions/env
@@ -80,10 +80,16 @@ source ~/.bash_profile
 update() {
   source "${project_path}/misc/rtorrent-docker.bash"
 
+  if [[ -f "${project_path}/data/env.engine" ]]; then
+    source "${project_path}/data/env.engine"
+  fi
+
   case "\${RDO_DOCKER_TYPE}" in
     machine)
       if [[ -f "${project_path}/data/env.machine" ]]; then
         source "${project_path}/data/env.machine"
+      else
+        echo "Missing '${project_path}/data/env.machine' file." >&2
       fi
       ;;
   esac
@@ -91,16 +97,21 @@ update() {
 
 export PATH="${project_path}:\${PATH}"
 export EXEC_PTY="$((command -v winpty) || (command -v console) || :)"
-export PROMPT_COMMAND+="; PS1=\"<\\\${DOCKER_MACHINE_NAME}> \\\${PS1}\""
 
 export RDO_BASH_SESSION="yes"
 export RDO_DOCKER_TYPE="${arg_docker_type}"
-
 EOF
 
   if [[ -n "${arg_docker_machine}" ]]; then
     cat >> "${DATA_PATH}/env.bash" <<EOF
 export RDO_DOCKER_MACHINE="${arg_docker_machine}"
+
+export PROMPT_COMMAND+="; PS1=\"<\\\${DOCKER_MACHINE_NAME}:\\\${DOCKER_CONTEXT}> \\\${PS1}\""
+EOF
+  else
+    cat >> "${DATA_PATH}/env.bash" <<EOF
+
+export PROMPT_COMMAND+="; PS1=\"<\\\${DOCKER_CONTEXT}> \\\${PS1}\""
 EOF
   fi
 
@@ -111,6 +122,7 @@ EOF
   fi
 
     cat >> "${DATA_PATH}/env.bash" <<EOF
+
 update
 EOF
 
