Fixed caching.

diff --git a/functions/env b/functions/env
--- a/functions/env
+++ b/functions/env
@@ -84,6 +84,15 @@ update() {
     machine)
       if [[ -f "${project_path}/data/env.machine" ]]; then
         source "${project_path}/data/env.machine"
+      else
+        echo "Missing '${project_path}/data/env.machine' file." >&2
+      fi
+      ;;
+    engine)
+      if [[ -f "${project_path}/data/env.engine" ]]; then
+        source "${project_path}/data/env.engine"
+      else
+        echo "Missing '${project_path}/data/env.engine' file." >&2
       fi
       ;;
   esac
@@ -91,7 +100,6 @@ update() {
 
 export PATH="${project_path}:\${PATH}"
 export EXEC_PTY="$((command -v winpty) || (command -v console) || :)"
-export PROMPT_COMMAND+="; PS1=\"<\\\${DOCKER_MACHINE_NAME}> \\\${PS1}\""
 
 export RDO_BASH_SESSION="yes"
 export RDO_DOCKER_TYPE="${arg_docker_type}"
@@ -100,12 +108,14 @@ EOF
 
   if [[ -n "${arg_docker_machine}" ]]; then
     cat >> "${DATA_PATH}/env.bash" <<EOF
+export PROMPT_COMMAND+="; PS1=\"<machine: \\\${DOCKER_MACHINE_NAME}> \\\${PS1}\""
 export RDO_DOCKER_MACHINE="${arg_docker_machine}"
 EOF
   fi
 
   if [[ -n "${arg_repository}" ]]; then
     cat >> "${DATA_PATH}/env.bash" <<EOF
+export PROMPT_COMMAND+="; PS1=\"<context: \\\${DOCKER_CONTEXT}> \\\${PS1}\""
 export RDO_REPOSITORY="${arg_repository}"
 EOF
   fi
